### ISSUE TITLE
allow for `includes` option for various modules and leverage dependency resolution

### ISSUE THREAD

**Issue by pyramation** [cosmology-tech/telescope#352]
while you can limit via the proto folders as input, could be useful to have a `proto.includes` as well as `includes` for various plugins

@clockworkgr can you provide any examples or code in ignite CLI that would be helpful?

**Comment by pyramation** [comment]
https://github.com/ignite/cli/blob/main/ignite/pkg/cosmosgen/generate_typescript.go#L176-L177

**Comment by clockworkgr** [comment]
After having a quick look through the codebase, I think the best/easiest thing to do here is leverage the `traverseAll()` call to filter down the store to the necessities.

Let's assume we have the following `.proto` files:

A.proto is module A and defines service A in `./proto/`
B.proto is module B and defines service B in `./proto/`
C.proto is a dependency of service A in `./deps/`
D.proto is a dependency of service B in `./deps/`
E.proto is an unrelated module E defining service E that we do not care about but also resides in `./deps/`

The idea is that we call CLI like so:

`telescope transpile --protoDirs ./proto --protoDirs ./deps --build ./proto` 

or even:

`telescope transpile --protoDirs ./proto --protoDirs ./deps --build ./proto/A.proto` 

i.e. we give it the protoDirs (include folders) to find everything necessary but explicitly tell it what to build...

current version would build types and clients for A, B AND E (along with necessary deps types)

Proposed version would only build for A and B.

Since traverseAll is ran at the end of the import process from what I can tell in order to verify deps, we can have it accept the list from `--build` and trim out any unnecessary imports.
